name: CLA Verified Gate

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  require-cla-verified-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for cla/verified label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            if (!labels.includes('cla/verified')) {
              core.setFailed('PR must be labeled with "cla/verified" before merging. A maintainer should verify the signed CLA and add this label.');
            } else {
              console.log('cla/verified label present.');
            }
