name: CLA check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-cla:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for CLA checkbox and attached CLA file
        env:
          PR_BODY: "${{ github.event.pull_request.body }}"
        run: |
          echo "Checking PR body for CLA confirmation..."
          echo "$PR_BODY" | grep -q "I have read and signed the `CLA.md`" || (
            echo "CLA not confirmed in PR body. Please sign the CLA and check the box in the pull request template.";
            exit 1
          )

      - name: Ensure a CLA-*.md file is added to the PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const files = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            const claFile = files.data.find(f => /(^|\/)CLA-[^\/]+\.md$/i.test(f.filename));
            if (!claFile) {
              const core = require('@actions/core');
              core.setFailed('No CLA-<your-name>.md file found in the PR. Attach a signed CLA file at the repository root.');
            } else {
              console.log('Found CLA file in PR:', claFile.filename);
              // fetch file contents from the PR head ref
              const ref = context.payload.pull_request.head.sha;
              try {
                const contentResp = await github.rest.repos.getContent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  path: claFile.filename,
                  ref,
                });
                let content = '';
                if (!contentResp || !contentResp.data) {
                  const core = require('@actions/core');
                  core.setFailed('Unable to fetch CLA file contents.');
                } else if (Array.isArray(contentResp.data)) {
                  const core = require('@actions/core');
                  core.setFailed('CLA path resolves to a directory unexpectedly.');
                } else {
                  content = Buffer.from(contentResp.data.content, contentResp.data.encoding).toString();
                  const signed = /<!--\s*CLA-SIGNED:\s*true\s*-->/i.test(content);
                  if (!signed) {
                    const core = require('@actions/core');
                    core.setFailed('CLA file found but not signed. Add <!-- CLA-SIGNED: true --> to the CLA-<your-name>.md file.');
                  } else {
                    console.log('CLA file is signed.');
                  }
                }
              } catch (err) {
                const core = require('@actions/core');
                core.setFailed('Error fetching CLA file: ' + err.message);
              }
            }
